# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wsumsq <- function(xx, yy, ww) {
    .Call('abcGWAS_wsumsq', PACKAGE = 'abcGWAS', xx, yy, ww)
}

